package constants

// log_templates.go 集中定义全部日志格式字符串（≥25 条），
// 任何 handler/service/middleware 必须引用这里的模板，禁止散落手写日志文案。
const (
	LOG_USER_REGISTER_START          = "User register start"
	LOG_USER_REGISTER_SUCCESS        = "User register success"
	LOG_USER_LOGIN_START               = "User login start"
	LOG_USER_LOGIN_SUCCESS           = "User login success"
	LOG_USER_LOGIN_FAILED            = "User login failed"
	LOG_USER_PROFILE_UPDATED         = "User profile updated"
	LOG_USER_AVATAR_UPLOADED         = "User avatar uploaded"
	LOG_FAMILY_GROUP_CREATED         = "FamilyGroup created"
	LOG_FAMILY_GROUP_UPDATED         = "FamilyGroup updated"
	LOG_FAMILY_MEMBER_INVITED        = "FamilyMember invited"
	LOG_FAMILY_MEMBER_JOINED         = "FamilyMember joined"
	LOG_FAMILY_MEMBER_ROLE_CHANGED   = "FamilyMember role changed"
	LOG_FAMILY_MEMBER_REMOVED        = "FamilyMember removed"
	LOG_FOOD_CREATED                 = "FoodItem created"
	LOG_FOOD_UPDATED                 = "FoodItem updated"
	LOG_FOOD_DELETED                 = "FoodItem deleted"
	LOG_FOOD_IMPORTED                = "FoodItem csv imported"
	LOG_FOOD_CONSUME_SUCCESS         = "FoodItem consume success"
	LOG_FOOD_CONSUME_FAILED          = "FoodItem consume failed"
	LOG_FOOD_STATUS_REFRESHED        = "FoodItem freshness status refreshed"
	LOG_CONSUMPTION_RECORDED         = "ConsumptionRecord recorded"
	LOG_CONSUMPTION_ANALYSIS         = "ConsumptionRecord analysis generated"
	LOG_NOTIFICATION_CREATED         = "Notification created"
	LOG_NOTIFICATION_READ            = "Notification read"
	LOG_EXPIRY_SCAN_STARTED          = "Expiry scan started"
	LOG_EXPIRY_SCAN_FINISHED         = "Expiry scan finished"
	LOG_EXPIRY_SCAN_FAILED           = "Expiry scan failed"
	LOG_EMAIL_SIMULATED              = "Email simulated sent"
	LOG_RECIPE_RECOMMENDED           = "Recipe recommended"
	LOG_STATS_DASHBOARD              = "Stats dashboard generated"
	LOG_STATS_REPORT                 = "Stats report generated"
	LOG_RATE_LIMITED                 = "Request rate limited"
	LOG_REQUEST_START                = "Request start"
	LOG_REQUEST_FINISH               = "Request finish"
	LOG_PANIC_RECOVERED              = "Panic recovered"
	LOG_DB_INITIALIZED               = "Database initialized"
	LOG_REDIS_CONNECTED              = "Redis connected"
	LOG_SERVER_STARTED               = "Server started"
	LOG_SERVER_SHUTDOWN              = "Server shutdown"
)
